#!/usr/bin/env python3

from climi.uuuu.ffff import schF_keys_, cyl_, prg_, pure_fn_, slctStrL_
from climi.uuuu.cccc import concat_cube_, cubesv_
import iris
import cf_units
from datetime import datetime
import numpy as np
import argparse
import os


_djn = os.path.join


def main():
    parser = argparse.ArgumentParser('contact data 05-06 and rcp')
    parser.add_argument("-v", "--var",
                        type=str, help="for these variables")
    parser.add_argument("-s", "--season",
                        type=str, help="for these seasons")
    parser.add_argument("-i", "--dir0",
                        type=str, help="directory for 05-06")
    parser.add_argument("-o", "--dir1",
                        type=str, help="directory for rcp")
    parser.add_argument("-k", "--skip",
                        type=int, help="SKIP for # less than K")
    args = parser.parse_args()
    dir0 = args.dir0 if args.dir0 else \
        '/nobackup/rossby26/users/sm_chali/DATA/energi/res/gwls/cordex/EUR11/'
    dir1 = args.dir1 if args.dir1 else \
        '/nobackup/rossby26/users/sm_chali/DATA/energi/res/h248/cordex/EUR11/'
    os.makedirs(dir1 + 'dddd', exist_ok=True)
    fns = schF_keys_(dir0, '_05-06')
    if args.var:
        fns = slctStrL_(fns, [args.var.split(',')])
    if args.season:
        fns = slctStrL_(fns, [args.season.split(',')])
    print(len(fns))
    for i, fn in enumerate(fns):
        if args.skip and i < args.skip:
            continue
        print(prg_(i, len(fns)), fn)
        fn_ = pure_fn_(fn).replace('_05-06', '')
        fn__ = _djn(dir1, '{}.nc'.format(fn_))
        if os.path.isfile(fn__):
            o = iris.load([fn,  fn__])
            o = concat_cube_(o)
            fn___ = _djn(dir1, 'dddd', '{}.nc'.format(fn_))
            print('save to', fn___)
            cubesv_(o, fn___)


if __name__ == '__main__':
    main()
