#!/usr/bin/env python3

from climi.uuuu.ffff import schF_keys_, cyl_, prg_, pure_fn_
from climi.uuuu.cccc import concat_cube_, cubesv_
import iris
import cf_units
from datetime import datetime
import numpy as np
import argparse
import os


def main():
    dir0 = '/nobackup/rossby26/users/sm_chali/DATA/energi/res/gwls/cordex/EUR11/ALL/'
    dir1 = '/nobackup/rossby26/users/sm_chali/DATA/energi/res/h248/cordex/EUR11/ALL/'
    os.makedirs(dir1 + 'dddd', exist_ok=True)
    fns = schF_keys_(dir0)[195:]
    print(len(fns))
    for i, fn in enumerate(fns):
        print(prg_(i, len(fns)), fn)
        fn_ = pure_fn_(fn).replace('_05-06', '')
        o = iris.load([fn, '{}{}.nc'.format(dir1, fn_)])
        o = concat_cube_(o)
        fn_ = '{}dddd/{}.nc'.format(dir1, fn_)
        print('save to', fn_)
        cubesv_(o, fn_)


if __name__ == '__main__':
    main()
