#!/usr/bin/env python3

from climi.uuuu.ffff import schF_keys_, cyl_, prg_, pure_fn_
from climi.uuuu.cccc import extract_byAxes_, y0y1_of_cube, rm_t_aux_cube,\
                            cubesv_
import iris
import cf_units
from datetime import datetime
import numpy as np
import argparse
import os


def main():
    parser = argparse.ArgumentParser("Repair time coord of season cubes")
    parser.add_argument("fld", type=str,
                        help="folder")
    args = parser.parse_args()
    fld = args.fld
    idir = fld if fld[-1] == '/' else '{}/'.format(fld)
    print(idir)
    os.makedirs(idir + 'dddd', exist_ok=True)
    fns = schF_keys_(idir, 'ndjf', '_1971-2006')
    print(len(fns))
    for i, fn in enumerate(fns):
        print(prg_(i+1, len(fns)), fn)
        o = iris.load_cube(fn)
        o = extract_byAxes_(o, 'time', np.s_[:-1])
        fn_ = '{}dddd/{}.nc'.format(idir, pure_fn_(fn).replace('_1971-2006',
                                                               '_1971-2005'))
        print('save to', fn_)
        cubesv_(o, fn_)


if __name__ == '__main__':
    main()
