#!/usr/bin/env python3

from climi.uuuu.ffff import schF_keys_, cyl_, prg_, pure_fn_
from climi.uuuu.cccc import extract_byAxes_, cubesv_
import iris
import numpy as np
import argparse
import os


def main():
    parser = argparse.ArgumentParser("Repair time coord of season cubes")
    parser.add_argument("fld", type=str,
                        help="folder")
    args = parser.parse_args()
    fld = args.fld
    idir = fld if fld[-1] == '/' else '{}/'.format(fld)
    print(idir)
    os.makedirs(idir + 'dddd', exist_ok=True)
    fns = schF_keys_(idir, 'ZeroCrossingDays_', 'season')
    print(len(fns))
    for i, fn in enumerate(fns):
        print(prg_(i, len(fns)), fn)
        #if i < 3138:
        #    continue
        o = iris.load_cube(fn)
        try:
            iris.coord_categorisation.add_season(o, 'time')
            fn_ = '{}dddd/{}.nc'.format(idir, pure_fn_(fn))
            print('save to', fn_)
            cubesv_(o, fn_)
        except:
            pass


if __name__ == '__main__':
    main()
