#!/usr/bin/env python3

from climi.uuuu.ffff import prg_, windds2uv_
from climi.uuuu.xxxx import *
import pandas as pd
import numpy as np
import igra
import os


_djn = os.path.join


def main():
    dir0 = '/home/clin/Documents/data/igra/v2/metadata'
    dir1 = '/home/clin/Documents/data/igra/v2/data'
    dir1_ = _djn(dir1, 'monthly')
    dir1__ = _djn(dir1, 'seasonal')
    dir1___ = _djn(dir1, 'annual')
    for i in (dir1_, dir1__, dir1___):
        os.makedirs(i, exist_ok=True)
    stations = igra.read.stationlist(_djn(dir0, 'igra2-station-list.txt'))
    _f = np.vectorize(lambda x, y: min(y, 2020) - max(x, 1975))
    A = (~pd.isna(stations.wmo)) \
            & (~pd.isna(stations.lat)) \
            & (~pd.isna(stations.lon)) \
            & (_f(stations.start, stations.end) > 40)
    stations[A].to_csv(_djn(dir0, 'monthly.csv'))
    nS = A[A].count()
    for i, sid in enumerate(stations[A].index):
        if i < 678:
            continue
        print(prg_(i, nS), sid)
        try:
            o, _ = igra.read.igra(sid, _djn(dir1, sid + '-data.txt.zip'))
            o = o.where(o.flag_int!=1)
            o = o.drop_vars('flag_int')
            o = uvds_(o)
            o = xr_daily_mean_(o, 2)
            o = xr_monthly_mean_(o, 10)
            o0 = xr_seasonal_mean_(o, 2)
            o1 = xr_annual_mean_(o, 9)
            o.to_netcdf(path=_djn(dir1_, sid + '.nc'))
            o0.to_netcdf(path=_djn(dir1__, sid + '.nc'))
            o1.to_netcdf(path=_djn(dir1___, sid + '.nc'))
        except:
            pass


if __name__ == '__main__':
    main()
