#!/usr/bin/env python3

import iris
from climi.uuuu import concat_cube_, cubesv_

def _to_o(i, var): 
    o = iris.load('/nobackup/rossby22/sm_chali/DATA/ECEARTH23/'
                  '{}_day_ECEARTH23_rcp85_r{}i1p1_*nc'.format(var, i)) 
    o0 = concat_cube_(o) 
    nc = iris.coords.AuxCoord(i, long_name='realization', units='no_unit') 
    o0.add_aux_coord(nc) 
    cubesv_(o0, '/nobackup/rossby22/sm_chali/DATA/hw2018/iii/other/'
                'eEC-EARTH/{}_ECEARTH23_RCP85_r_{}_cube.nc'.format(var, i),
            zlib=True, complevel=6)


def main():
    for var in ('pr',):
        for i in range(8,17):
            _to_o(i, var)


if __name__ == '__main__':
    main()
