#!/usr/bin/env python3

import climi.uuuu as u
import iris
import argparse
import os


def main():
    parser = argparse.ArgumentParser("LandMask cubes in other directory")
    parser.add_argument("keys", type=str, nargs='+',
                        help="keys to search files")
    parser.add_argument("-p", "--pctl", type=str, default='90',
                        help="percentile threshold")
    args = parser.parse_args()
    keys = args.keys
    p = args.pctl
    print(keys)
    idir = '/nobackup/rossby22/sm_chali/DATA/hc/res/other/{}/'.format(p)
    os.makedirs('{}msk/'.format(idir), exist_ok=True)
    ldir = '/nobackup/rossby22/sm_chali/DATA/fx/'
    print(idir)
    fns = u.schF_keys_(idir, *keys)
    print(len(fns))
    for i, fn in enumerate(fns):
        print(u.prg_(i+1, len(fns)), fn)
        m = u.pure_fn_(fn).split('_')[1]
        o = iris.load_cube(fn)
        l = u.load_fx_(ldir, m)
        u.maskLS_cube(o, l['sftlf'], thr=50.)
        fn_ = '{}msk/{}.nc'.format(idir, u.pure_fn_(fn))
        print('save to', fn_)
        iris.save(o, fn_)


if __name__ == '__main__':
    main()
