#!/usr/bin/env python3

import climi.uuuu as u
import iris
import pickle


def main():
    ldir = '/nobackup/rossby22/sm_chali/DATA/fx/'
    odir = '/home/sm_chali/wks/heat-wave-2018/climi/regriders/'
    GCMs = ['EC-EARTH', 'HadGEM2-ES', 'NorESM1-M']
    RCMs = ['SMHI-RCA4', 'DMI-HIRHAM5', 'KNMI-RACMO22E', 'GERICS-REMO2015']
    fnt = u.slctStrL_(u.schF_keys_(ldir, 'sftlf_fx_'),
                      incl=['_{}_'.format(i) for i in GCMs], incl_or=True)
    fns = u.slctStrL_(u.schF_keys_(ldir, 'ECMWF-ERAINT_evaluation'),
                      incl=['_{}_'.format(i) for i in RCMs], incl_or=True)
    #o0 = iris.load_cube(fn0)
    rd = {'longitude': [-10., 30.], 'latitude': [35., 70.]}
    print(len(fnt), len(fns))
    for i, fn0 in enumerate(fnt):
        print(u.prg_(i, len(fnt)), fn0)
        mdl0 = u.pure_fn_(fn0).split('_')[2]
        o0 = u.intersection_(iris.load_cube(fn0), **rd)
        for ii, fn in enumerate(fns):
            print(u.prg_(ii, len(fns)), fn)
            mdl = u.pure_fn_(fn).split('_')[5]
            o = iris.load_cube(fn)
            #o = iris.load_cube(fn)
            regrider = u.POLYrgd(o, o0)
            regrider._info()
            fn_ = '{}{}_{}_EUR.p'.format(odir, mdl, mdl0)
            print('save to', fn_)
            with open(fn_, 'wb') as f:
                pickle.dump(regrider, f, protocol=pickle.HIGHEST_PROTOCOL)


if __name__ == '__main__':
    main()
