#!/usr/bin/env python3


import climi.uuuu as u
import numpy as np
import iris

import os


y0, y1 = 1950, 1988

def main():
    c = u.extract_period_cube(
            iris.load_cube(
                '/home/rossby/imports/obs/EOBS/EOBS20/orig/'
                'tx_ens_mean_0.1deg_reg_v20.0e.nc'),
            y0, y1)
    cc = u.doy_f_cube(c, np.nanpercentile, f_Args=(90,), ws=15, mF=np.nan)
    iris.save(cc,
              '/nobackup/rossby22/sm_chali/DATA/hc/med/'
              'thr_tx_EOBS20_ALL_{}-{}_90.nc'.format(y0, y1))


if __name__ == '__main__':
    main()
