#!/usr/bin/env python3

import matplotlib as mpl
mpl.use('pdf', force=True)
import matplotlib.pyplot as plt
import numpy as np
import argparse
import yaml
import os
import warnings
import datetime
import iris
from iris.fileformats.netcdf import UnknownCellMethodWarning
from climi.pppp import *
from climi.uuuu import *
from climi.uuuu.cccc import _get_ind_lolalim as lllim_


_here_ = get_path_(__file__)


_djn = os.path.join


def _cmnm(bd, var):
    bd = np.asarray(bd)
    if 'PR' in var:
        cmap = mpl.cm.RdGy
    else:
        cmap = mpl.cm.RdGy_r
    norm = mpl.colors.BoundaryNorm(bd, cmap.N, extend='both')
    return dict(cmap=cmap, norm=norm)


def _pdict(var):
    return  _cmnm([-.6, -.5, -.4, -.3,  .3, .4, .5, .6], var)


def _rf(fn):
    if os.path.isfile(fn):
        return iris.load_cube(fn)


def _clcdx(ddir, gcms, rcms, y0y1, freq, var0, var1, var2):
    ffmt = '{}pcc_r_{}_{}_{}-{}_{}_{}-{}-{}.nc'
    o = []
    for gcm in gcms:
        oo = []
        for rcm in rcms:
            oo.append(_rf(ffmt.format(ddir, gcm, rcm, *y0y1, freq,
                                      var0, var1, var2)))
        o.append(oo)
    return o


def _clcmp(ddir, gcms, y0y1, freq, var0, var1, var2, go_='g'):
    ffmt = '{}pcc_{}_{}_{}-{}_{}_{}-{}-{}.nc'
    o = []
    for gcm in gcms:
        o.append(_rf(ffmt.format(ddir, go_, gcm, *y0y1, freq,
                                 var0, var1, var2)))
    return o


def _pch(fig, nrow, ncol, ii, o, rgD, pD, tiD=None, xi=None, yi=None):
    ax, pch = pch_ll_(fig, nrow, ncol, ii, o,
                       rg=rgD, pcho=pD, fr_on=True)
    if xi:
        ax.set_title(xi, tiD)
    if yi:
        axp = ax.get_position()
        fig.text(axp.x0 - .01, (axp.y0 + axp.y1)/2, yi,
                 ha='center', va='baseline',
                 rotation_mode='anchor', rotation='vertical',
                 **tiD)
    return (ax, pch)


def _xiyi(fig, nrow, ncol, ii, tiD=None, xi=None, yi=None):
    ax = fig.add_subplot(nrow, ncol, ii)
    axVisibleOff_(ax)
    ax.set_yticks([])
    ax.set_xticks([])
    if xi:
        ax.set_title(xi, tiD)
    if yi:
        axp = ax.get_position()
        fig.text(axp.x0 - .01, (axp.y0 + axp.y1)/2, yi,
                 ha='center', va='baseline',
                 rotation_mode='anchor', rotation='vertical',
                 **tiD)


def _tx_rgmean(fig, ax, cube, rgD):
    s = '{:.1f}'.format(rgMean_cube(cube, rgD=rgD).data)
    aligned_tx_(fig, ax, s, rpo='tl', itv=-0.005, alpha=.5, fontsize=8)


def _mp0(fn, cgL, crLL, gcms, rcms, pD, rgD, vl, coL=None, obss=None):
    tiD = dict(fontsize=10, fontweight='bold')
    nrow = len(gcms) + (1 if coL else 0)
    ncol = len(rcms) + 1
    pD_ = dict(rasterized=True)
    pD_.update(pD)
    fx = 7.5
    ifx = fx/ncol
    fy = ifx * .8 * nrow
    fig = init_fig_(fx=fx, fy=fy, l=.04, r=.87, t=.91 if coL else .93, b=.02)
    def _p(ii, o, xi=None, yi=None):
        return _pch(fig, nrow, ncol, ii, o, rgD, pD_, tiD, xi, yi)
    axs, axr = [], []
    if coL:
        i_ = 1
        axo = []
        for i, (cube, xi) in enumerate(zip(coL, obss)):
            if cube:
                ax, pch = _p(i + 1, cube, xi)
                ax_move_(ax, dy=.04)
                axo.append(ax)
                _tx_rgmean(fig, ax, cube, rgD)
    else:
        i_ = 0
    for i, (cg, crL, yi) in enumerate(zip(cgL, crLL, gcms)):
        for ii, (cube, xi) in enumerate(zip([cg] + crL,
                                            ['Driving data'] + rcms)):
            xi_ = xi if i == 0 else None
            yi_ = yi if ii == 0 else None
            if cube:
                ax, pch = _p((i + i_) * ncol + ii + 1, cube, xi_, yi_)
                axs.append(ax)
                if xi in rcms:
                    axr.append(ax)
                _tx_rgmean(fig, ax, cube, rgD)
            else:
                _xiyi(fig, nrow, ncol, (i + i_) * ncol + ii + 1, tiD, xi_, yi_)
    axs_rct_(fig, axr, color='r')
    cbw = wspace_ax_(*axs[-2:])
    if i_:
        axs += axo
    cb = aligned_cb_(fig, axs, pch, [cbw, .02], shrink=.5,
                     orientation='vertical', extend='both')
    cb.set_label(vl)
    #fig.tight_layout()
    plt.savefig(fn, dpi=300)
    plt.close()


def main():
    #warnings.filterwarnings("ignore", category=UserWarning)
    warnings.filterwarnings("ignore", category=UnknownCellMethodWarning)
    with open(_djn(_here_, 'cfg_plt_hwmid_h8.yml'), 'r') as ymlfile:
        cfg = yaml.safe_load(ymlfile)
    #output dirs
    ddir = cfg['ddir']# + 'interp_/'
    fdir = cfg['fdir']# + 'interp_/'
    tdir = cfg['tdir']
    os.makedirs(ddir, exist_ok=True)
    os.makedirs(fdir, exist_ok=True)
    os.makedirs(tdir, exist_ok=True)
    #constans
    obss = cfg['obss']
    gcms = cfg['gcms_']
    rcms = cfg['rcms_']
    rcms.sort()
    rcp, ref, rgDs = cfg['rcp'], cfg['ref'], cfg['rgDs']
    idir = cfg['idir']['obss']
    idir_ = cfg['idir']['gcms']
    idir__ = cfg['idir']['rcms']
    rgD_eur = rgDs['eur']
    #loop variables
    vv = ['hwmid-tx']
    ff = ['j-d']
    yy = ['mean']
    pp = [[1981, 2100]]
    #pp = [[1981, 2020], [2021, 2060], [2061, 2100]]
    VV = ['EffPR', 'DryDays']
    var2 = 'TX'
    #vv = ['hwmid-tn']
    #yy = ['g15', 'mean']
    #loop 0
    for var0 in vv:
        print('{}'.format(var0))
        #loop 1
        for var1 in VV:
            print('{}'.format(var1))
            for freq in ff:
                print('  {}'.format(freq))
                for y0y1 in pp:
                    print('    {}-{}'.format(*y0y1))
                    vl = 'Correlation coeficient'
                    pD = _pdict(var1)
                    fn = '{}pcc_p{}-{}_{}-{}.pdf'.format(fdir, *y0y1,
                                                        var0, var1, var2)
                    crLL = _clcdx(ddir, gcms, rcms, y0y1, freq,
                                  var0, var1, var2)
                    cgL = _clcmp(ddir, gcms, y0y1, freq, var0, var1, var2)
                    #print(ddir)
                    #################
                    A2, TFx, TFy = compressLL_(crLL)
                    A1 = l_ind_(cgL, TFy)
                    A3 = l_ind_(gcms, TFy)
                    A4 = l_ind_(rcms, TFx)
                    #print(A1, A2)
                    #################
                    if y0y1[0] < 2021:
                        coL = _clcmp(ddir, obss, [1981, 2020],
                                     freq, var0, var1, var2, 'o')
                        print(coL)
                        if not all([i is None for i in coL]):
                            B1, B2 = zip(*[(i, ii) for i, ii in zip(coL, obss)
                                           if i is not None])
                            _mp0(fn,
                                 A1, A2, A3, A4, pD, rgD_eur, vl,
                                 B1, B2)
                        else:
                            _mp0(fn, A1, A2, A3, A4, pD, rgD_eur, vl)
                    else:
                        _mp0(fn, A1, A2, A3, A4, pD, rgD_eur, vl)


if __name__ == '__main__':
    main()
