#!/usr/bin/env python3

import numpy as np
import geopandas as gpd
import matplotlib as mpl
mpl.use('pdf', force=True)
import matplotlib.pyplot as plt
import iris
import os
import time
import logging
import warnings
import argparse
import yaml

from time import localtime, strftime

from climi.uuuu import *
from climi.pppp import *


_here_ = get_path_(__file__)


_djn = os.path.join


def _fnfmt(idir, *terms, ext='.pdf'):
    nm_ = '_'.join(i for i in terms if i) + ext
    return _djn(idir, nm_)


def _shps(n):
    shp = gpd_read(_djn(_here_, 'swe_districts/distriktsanalys_polygon.shp'))
    shp_ = shp.to_crs(epsg=4326)
    idd = shp.ID.copy()
    idd.loc[:] = 0.
    for i in range(n):
        idd = idd.rename('mean{}'.format(i))
        shp = gpd.pd.concat((shp, idd), axis=1)
    for i in range(n):
        idd = idd.rename('iqr{}'.format(i))
        shp = gpd.pd.concat((shp, idd), axis=1)
    return (shp, shp_)


def _minmax_df(df):
    data_ = df.to_numpy()
    return (np.nanmin(data_), np.nanmax(data_))


def _cmp01(unit, var):
    if unit == 'K' or var in ('RLDS', 'RSDS', 'SD', 'TropicNights',
                              'ConWarmDays', 'HumiWarmDays', 'WarmDays'):
        cmp0 = 'coolwarm'
        cmp1 = 'coolwarm'
    elif var in ('DryDays', 'LnstDryDays'):
        cmp0 = 'YlGnBu_r'
        cmp1 = 'BrBG_r'
    elif unit == 'days':
        cmp0 = 'cubehelix'
        cmp1 = 'PRGn_r'
    else:
        cmp0 = 'YlGnBu'
        cmp1 = 'BrBG'
    return (cmp0, cmp1)


def _map(shp0, dn, gwls, unit, odir, var, freq, fig_dict=None):
    #################################################################parameters
    ngwls = gwls + [r'{} $-$ {}'.format(gwl, gwls[0]) for gwl in gwls[1:]]
    nrow = 2
    na, nb = len(gwls), len(ngwls) - len(gwls)
    if na > 4:
        nrow = 4
        ncol = na
        n0, n1, n2, n3 = 1, 2 + ncol, 1 + ncol * 2, 2 + ncol * 3
        dx = None
    else:
        nrow = 2
        ncol = na + nb
        n0, n1, n2, n3 = 1, 1 + na, 1 + ncol, 1 + ncol + na
        dx = 1 / (ncol + 1.25) - 1 / ncol #rx = .85
    pch_dict = {'cmap': 'YlGnBu'}
    tD = dict(fontsize=10 if ncol > 5 else 14)
    cmp0, cmp1 = _cmp01(unit, var)

    min0, max0 = _minmax_df(shp0.loc[:, ['mean{}'.format(i)
                                         for i in range(na)]])
    min1, max1 = _minmax_df(shp0.loc[:, ['iqr{}'.format(i)
                                         for i in range(na)]])
    min2, max2 = _minmax_df(shp0.loc[:, ['mean{}'.format(i)
                                         for i in range(na, na + nb)]])
    min3, max3 = _minmax_df(shp0.loc[:, ['iqr{}'.format(i)
                                         for i in range(na, na + nb)]])
    mm2 = np.max(np.abs([min2, max2]))

    ########################################################################fig
    if fig_dict:
        fig = init_fig_(**fig_dict)
    else:
        fig = init_fig_(h=.02, w=.05, t=.95, b=.025, l=.01, r=.95)

    #########################################################################ax
    axs = []
    pch_dict.update({'vmin': min0, 'vmax': max0, 'cmap': cmp0})
    for i in range(na):
        ax = distri_swe_(fig, nrow, ncol, i + n0, shp0,
                         column='mean{}'.format(i), pcho=pch_dict)
        ax.set_title(gwls[i], tD)
        axs.append(ax)
    pch_dict.update({'vmin': -mm2, 'vmax': mm2, 'cmap': cmp1})
    for i in range(nb):
        ax = distri_swe_(fig, nrow, ncol, i + n1, shp0,
                         column='mean{}'.format(i + na), pcho=pch_dict)
        ax.set_title(ngwls[i + na], tD)
        axs.append(ax)
    pch_dict.update({'vmin': min1, 'vmax': max1, 'cmap': cmp0})
    for i in range(na):
        ax = distri_swe_(fig, nrow, ncol, i + n2, shp0,
                         column='iqr{}'.format(i), pcho=pch_dict)
        axs.append(ax)
    pch_dict.update({'vmin': min3, 'vmax': max3, 'cmap': cmp0})
    for i in range(nb):
        ax = distri_swe_(fig, nrow, ncol, i + n3, shp0,
                         column='iqr{}'.format(i + na), pcho=pch_dict)
        axs.append(ax)

    ###################################################################colorbar
    if dx:
        axs_move_(axs[:na], dx)
        axs_move_(axs[na:(na + nb)], dx)
        axs_move_(axs[(na + nb):(na * 2 + nb)], dx)
        axs_move_(axs[(na * 2 + nb): (na + nb) * 2], dx)
    cb = aligned_cb_(fig, axs[na - 1], get_1st_patchCollection_(axs[na - 1]),
                     [.01, .0125], orientation='vertical')
    cb.set_label('{} ({})'.format(var, unit))
    cb2 = aligned_cb_(fig, axs[na + nb - 1],
                      get_1st_patchCollection_(axs[na + nb - 1]),
                      [.01, .0125], orientation='vertical')
    cb2.set_label('$\Delta${} ({})'.format(var, unit))
    cbz = aligned_cb_(fig, axs[na * 2 + nb - 1],
                      get_1st_patchCollection_(axs[na * 2 + nb - 1]),
                      [.01, .0125], orientation='vertical')
    cbz.set_label('{} IQR ({}) N={}'.format(var, unit, len(dn)))
    cbz2 = aligned_cb_(fig, axs[-1], get_1st_patchCollection_(axs[-1]),
                       [.01, .0125], orientation='vertical')
    cbz2.set_label('$\Delta${} IQR ({}) N={}'.format(var, unit, len(dn)))

    ####################################################################to file
    plt.savefig(_fnfmt(odir, 'mapX', var, freq), dpi=300)
    plt.close()


def bp__(ts, dn, unit, gwls, odir, var, freq, opt='0', ap=None):
    if len(dn[0].split('_')) == 3:
        ll = map_sim_cmip5_(dn)
    else:
        ll = map_sim_(dn)
    ########################################################################bp0
    if '0' in opt:
        fig = init_fig_(fx=16, l=.05, r=.95, t=0.8)
        ax_opt = {'ylabel': '{} ({})'.format(var, unit)}
        ax0 = fig.add_subplot(1, 1, 1, **ax_opt)
        h_ = bp_dataLL0_(ax0, ts, labels=gwls)
        ax0.legend(h_, ll + ['ENSEMBLE'], bbox_to_anchor=(0., 1.01, 1., 0.18),
                   loc='lower left',
                   borderaxespad=0, ncol=15, mode='expand')
        pn = 'bp0-{}'.format(ap) if ap else 'bp0'
        plt.savefig(_fnfmt(odir, pn, var, freq), dpi=300)
        plt.close()

    ########################################################################bp1
    if '1' in opt:
        fig = init_fig_()
        ax_opt = {'ylabel': '{} ({})'.format(var, unit)}
        ax0 = fig.add_subplot(1, 1, 1, **ax_opt)
        h_ = bp_dataLL1_(ax0, ts, labels=gwls)

        ax0.legend(h_, ['ENSEMBLE'])

        pn = 'bp1-{}'.format(ap) if ap else 'bp1'
        plt.savefig(_fnfmt(odir, pn, var, freq), dpi=300)
        plt.close()

    ########################################################################bp2
    if '2' in opt:
        fig = init_fig_(fx=16, l=.05, r=.975, b=.1)
        ax_opt = {'ylabel': '{} ({})'.format(var, unit)}
        ax0 = fig.add_subplot(2, 1, 1, **ax_opt)
        ax_opt.update({'ylabel': '$\Delta${} ({})'.format(var, unit)})
        ax1 = fig.add_subplot(2, 1, 2, **ax_opt)
        h0_ = bp_dataLL_(ax0, ts, labels=None)
        h1_ = bp_dataLL_(ax1, [di - ts[0] for di in ts[1:]],
                         labels=ll)
        lgo = dict(ncol=len(gwls)) if len(gwls) > 3 else dict()
        ax0.legend(h0_, gwls, **lgo)
        lgo = dict(ncol=len(gwls) - 1) if len(gwls) > 3 else dict()
        ax1.legend(h1_, [r'{} $-$ {}'.format(gwl, gwls[0])
                         for gwl in gwls[1:]], **lgo)

        pn = 'bp2-{}'.format(ap) if ap else 'bp2'
        plt.savefig(_fnfmt(odir, pn, var, freq), dpi=300)
        plt.close()


def map__(am, ai, bm, bi, dn, gwls, unit, rg_dict, odir, var, freq,
          pch__=None, fig_dict=None, ap=None):
    ##############################################################plot function
    if pch__ is None:
        pch__ = pch_swe_

    #################################################################parameters
    dgwls = [r'{} $-$ {}'.format(gwl, gwls[0]) for gwl in gwls[1:]]
    na, nb = len(gwls), len(dgwls)
    if na > 4:
        nrow = 4
        ncol = na
        n0, n1, n2, n3 = 1, 2 + ncol, 1 + ncol * 2, 2 + ncol * 3
        dx = None
    else:
        nrow = 2
        ncol = na + nb
        n0, n1, n2, n3 = 1, 1 + na, 1 + ncol, 1 + ncol + na
        dx = 1 / (ncol + 1.25) - 1 / ncol #rx = .85
    tD = dict(fontsize=10 if ncol > 5 else 14)
    pch_dict = dict(cmap='YlGnBu',rasterized=True)
    cmp0, cmp1 = _cmp01(unit, var)

    min0, max0 = minmax_cube_(am, rg=rg_dict, p=5)
    min1, max1 = minmax_cube_(ai, rg=rg_dict, p=5)
    min2, max2 = minmax_cube_(bm, rg=rg_dict, p=5)
    min3, max3 = minmax_cube_(bi, rg=rg_dict, p=5)
    mm2 = np.max(np.abs([min2, max2]))

    ########################################################################fig
    if fig_dict:
        fig = init_fig_(**fig_dict)
    else:
        fig = init_fig_(h=.02, w=.05, t=.95, b=.025, l=.01, r=.95)

    #########################################################################ax
    axs, pchs = [], []
    pch_dict.update({'vmin': min0, 'vmax': max0, 'cmap': cmp0})
    for i in range(na):
        ax, pch = pch__(fig, nrow, ncol, i + n0, am[i],
                        rg=rg_dict, pcho=pch_dict)
        ax.set_title(gwls[i], tD)
        axs.append(ax)
        pchs.append(pch)
    pch_dict.update({'vmin': -mm2, 'vmax': mm2, 'cmap': cmp1})
    for i in range(nb):
        ax, pch = pch__(fig, nrow, ncol, i + n1, bm[i],
                        rg=rg_dict, pcho=pch_dict)
        ax.set_title(dgwls[i], tD)
        axs.append(ax)
        pchs.append(pch)
    pch_dict.update({'vmin': min1, 'vmax': max1, 'cmap': cmp0})
    for i in range(na):
        ax, pch = pch__(fig, nrow, ncol, i + n2, ai[i],
                        rg=rg_dict, pcho=pch_dict)
        axs.append(ax)
        pchs.append(pch)
    pch_dict.update({'vmin': min3, 'vmax': max3, 'cmap': cmp0})
    for i in range(nb):
        ax, pch = pch__(fig, nrow, ncol, i + n3, bi[i],
                        rg=rg_dict, pcho=pch_dict)
        axs.append(ax)
        pchs.append(pch)

    ###################################################################colorbar
    if dx:
        axs_move_(axs[:na], dx)
        axs_move_(axs[na:(na + nb)], dx)
        axs_move_(axs[(na + nb):(na * 2 + nb)], dx)
        axs_move_(axs[(na * 2 + nb): (na + nb) * 2], dx)
    cb = aligned_cb_(fig, axs[na - 1], pchs[na - 1], [.01, .0125],
                     orientation='vertical')
    cb.set_label('{} ({})'.format(var, unit))
    cb2 = aligned_cb_(fig, axs[na + nb - 1], pchs[na + nb - 1], [.01, .0125],
                      orientation='vertical')
    cb2.set_label('$\Delta${} ({})'.format(var, unit))
    cbz = aligned_cb_(fig, axs[na * 2 + nb - 1], pchs[na * 2 + nb - 1],
                      [.01, .0125], orientation='vertical')
    cbz.set_label('{} IQR ({}) N={}'.format(var, unit, len(dn)))
    cbz2 = aligned_cb_(fig, axs[-1], pchs[-1], [.01, .0125],
                       orientation='vertical')
    cbz2.set_label('$\Delta${} IQR ({}) N={}'.format(var, unit, len(dn)))

    ####################################################################to file
    fn = 'map-{}'.format(ap) if ap else 'map'
    plt.savefig(_fnfmt(odir, fn, var, freq), dpi=300)
    plt.close()


def id__(cubeLL, dn, gwls, sc, unit, odir, var, freq, shp, shp_,
         fig_dict=None):
    shp0 = shp.copy()
    ids = set(shp0.ID)
    for i in ids:
        svd = poly_to_path_(list(shp_.loc[shp_.ID == i, 'geometry']))
        ##########################################################fixing SNWmax
        if var in ['SNWmax', 'R5OScw', 'R1OScw'] and i in [12, 15]:
            a_, dn_ = slct_cubeLL_dnL_(cubeLL, dn, slctStrL_, excl='KNMI')
            ts = get_ts_clmidx_(a_, dn_, sc, poly=svd)
            bp__(ts, dn_, unit, gwls, odir, var, freq, opt='0',
                 ap='ID{}'.format(i))
        ##########################################################fixing SNWmax
        else:
            ts = get_ts_clmidx_(cubeLL, dn, sc, poly=svd)
            bp__(ts, dn, unit, gwls, odir, var, freq, opt='0',
                 ap='ID{}'.format(i))
        ts0 = ts + [ii - ts[0] for ii in ts[1:]]
        ts1 = np.asarray([np.nanmean(ii, axis=-1) for ii in ts0])
        m_ = np.nanmean(ts1, axis=-1)
        iqr_ = (np.nanpercentile(ts1, 75, axis=-1) -
                np.nanpercentile(ts1, 25, axis=-1))
        for ii in range(len(m_)):
            shp0.loc[shp_.ID==i, 'mean{}'.format(ii)] = m_[ii]
            shp0.loc[shp_.ID==i, 'iqr{}'.format(ii)] = iqr_[ii]
    _map(shp0, dn, gwls, unit, odir, var, freq, fig_dict=fig_dict)


def _q_file(odir__, cubeLL, sc, freq, gwls, cref=None):
    fnam = [_fnfmt(odir__, 'am', freq, i, ext='.nc')
            for i in ['current'] + gwls]
    fnai = [_fnfmt(odir__, 'ai', freq, i, ext='.nc')
            for i in ['current'] + gwls]
    fnbm = [_fnfmt(odir__, 'bm', freq, i, ext='.nc') for i in gwls]
    fnbi = [_fnfmt(odir__, 'bi', freq, i, ext='.nc') for i in gwls]
    if all([os.path.isfile(i) for i in fnam + fnai + fnbm + fnbi]):
        am, ai, bm, bi = [[iris.load_cube(ii) for ii in i]
                          for i in (fnam, fnai, fnbm, fnbi)]
    else:
        msk = cref.data.mask if (cref and np.ma.isMaskedArray(cref.data) and
                                 np.ma.is_masked(cref.data)) else None
        os.makedirs(odir__, exist_ok=True)
        am, ai, bm, bi = get_clm_clmidx_(cubeLL, sc, cref=cref)
        for i, ii in zip((am, ai, bm, bi), (fnam, fnai, fnbm, fnbi)):
            for i_, ii_ in zip(i, ii):
                if msk is not None:
                    i_ = iris.util.mask_cube(i_, robust_bc2_(msk, i_.shape))
                iris.save(i_, ii_)
    return (am, ai, bm, bi)




def main():
    warnings.filterwarnings("ignore", category=UserWarning)
    mpl.style.use('seaborn')
    #####################################################################PARSER
    parser = argparse.ArgumentParser('PLOT CLIMIDX')
    parser.add_argument("opt", type=int, default=0,
                        help="options for dataset on BI")
    parser.add_argument("-y", "--yml",                                          
                        type=str,                                               
                        help="yml file defining freqs for each index")
    parser.add_argument("-c", "--config", type=str, default="2", help="")
    parser.add_argument("-s", "--start", type=int, help="")
    parser.add_argument("-e", "--end", type=int, help="")
    parser.add_argument("-l", "--log", type=str, default="", help="")
    args = parser.parse_args()
    opt_, log_ = args.opt, args.log
    sss_, eee_ = args.start, args.end
    ####################################################################LOGGING
    lfn = 'plt-{}-{}'.format(opt_, log_)
    nlog = len(schF_keys_('', lfn, ext='.log'))
    logging.basicConfig(filename='{}{}.log'.format(lfn, '_' * nlog),
                        filemode='w',
                        level=logging.INFO)
    logging.info(' {:_^42}'.format('start of program'))
    logging.info(strftime(" %a, %d %b %Y %H:%M:%S +0000", localtime()))
    logging.info(' ')
    ##################################################################CONFIGURE
    if os.path.isfile(args.config):
        yf = args.config
    elif args.config == '2':
        yf = _djn(_here_, 'cfg_plt_climidx_gwls2.yml')
    elif args.config == '3':
        yf = _djn(_here_, 'cfg_plt_climidx_gwls3.yml')
    elif args.config == '4':
        yf = _djn(_here_, 'cfg_plt_climidx_gwls4.yml')
    else:
        raise ValueError("unknown configuration!")
    with open(yf, 'r') as ymlfile:
        cfg = yaml.safe_load(ymlfile)
    version = cfg['version']
    gg, gwls = cfg['gg'], cfg['gwls']
    #gg = ['gwl15', 'gwl2']
    #gwls = ['current', '1.5 K warming', '2 K wariming']
    #gg = ['gwl15', 'gwl2', 'gwl25', 'gwl3', 'gwl35', 'gwl4']
    #gwls = ['current', '1.5 K warming', '2 K wariming', '2.5 K warming',
    #                    '3 K wariming', '3.5 K warming', '4 K warming']
    root = cfg['root']
    ddir, fxdir = cfg['ddir'], cfg['fxdir']
    ######################################################INDEPENDENT VARIABLES
    yml_ = args.yml
    if yml_ and os.path.isfile(yml_):                                           
        vf = yml_                                                               
    elif yml_ and os.path.isfile(_djn(_here_, yml_)):                   
        vf = _djn(_here_, yml_)                                         
    else:                                                                       
        vf = _djn(_here_, 'var_dict.yml')                               
    with open(vf, 'r') as ymlfile:                                              
        vdict = yaml.safe_load(ymlfile)
    yf = _djn(_here_, 'rg_dict.yml')
    with open(yf, 'r') as ymlfile:
        rdict = yaml.safe_load(ymlfile)
    #######################################VARIABLES VARY CORRISPONDING TO OPT_
    #rn = 'EUR' if opt_ in (0, 1) else 'GLB'
    #idir = '{}{}/'.format(ddir, rn)
    rn = None
    idir = _djn(ddir, 'cordex/EUR11' if opt_ in (0, 1) else 'cmip5')
    odir = _djn(root, 'DATA/energi/', version,
                        'fig{}K/'.format(gg[-1][3:]))
    _rn = 'SWE/' if opt_ == 0 else ('EUR/' if opt_ == 1 else 'SS/')
    _od0 = lambda x: _djn(odir, x, _rn)
    _od1 = lambda x: _djn(odir.replace('/fig', '/nc'), x)
    #r24 = os.environ.get('r24')
    #odir = '{}DATA/energi/2/fig{}K/'.format(r24, gg[-1][3:])
    #os.makedirs(odir, exist_ok=True)
    #idir = '/nobackup/rossby22/sm_chali/DATA/energi/res/gwls/EUR/'
    #fxdir = '/nobackup/rossby22/sm_chali/DATA/fx/'
    if opt_ == 0:
        ne50 = gpd_read(_djn(_here_, 'ne_50m/ne_50m_admin_0_countries.shp'))
        sv = poly_to_path_(list(ne50.loc[ne50.NAME=='Sweden', 'geometry']))
        shp, shp_ = _shps(len(gwls) * 2 - 1)
        rD_map = rdict[0]['SWE']
        if len(gwls) == 3:
            figD = None
        elif len(gwls) < 5:
            figD = dict(fx=len(gwls) * 4, h=.05, w=.1,
                        t=.95, b=.02, l=.01, r=.98)
        else:
            figD = dict(fx=len(gwls) * 2, fy=12,
                        h =.15, w=.01, t=.95, b=.02, l=.01, r=.925)
        mD = dict(fig_dict=figD)
    else:
        rD_map = rdict[0]['EUR']
        ix = 2.5 if opt_ == 1 else 2.75
        if len(gwls) < 5:
            figD = dict(fx=len(gwls) * ix * 2,
                        h=.02, w=.15, t=.925, b=.025, l=.01, r=.98)
        else:
            figD = dict(fx=len(gwls) * ix, fy=12,
                        h=.15, w=.01, t=.95, b=.02, l=.01, r=.925)
        mD = dict(pch__=pch_eur_, fig_dict=figD, ap='EUR') if opt_ == 1 else\
             dict(pch__=pch_ll_, fig_dict=figD, ap='EUR')
    if opt_ in (0, 1):
        vvv_ = list(vdict['freq_cfg'].keys())[sss_:eee_]
        lD = dict()
        tsD = dict(fxdir=fxdir)
        cref = iris.load_cube(_djn(fxdir, 'sftlf_EUR-11_ECMWF-ERAINT_'
                                           'evaluation_r0i0p0_SMHI-RCA4_v1_'
                                           'fx.nc'))
    else:
        vvv_ = ['SST', 'SIC']
        tsD = lD = dict(folder='cmip5')
        cref = iris.load_cube(_djn(fxdir, 'sftlf_fx_HadGEM2-ES_'
                                           'historical_r0i0p0.nc'))
    #############################################################FREQS & SUBDIR
    def _get_freq(var):
        def _sm(x):                                                             
            if x == 'season':                                                   
                return ['djf', 'mam', 'jja', 'son']                             
            elif x == 'month':                                                  
                return ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',               
                        'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']               
            else:                                                               
                return x                                                        
        freqs = ouniqL_(flt_l([_sm(i) for i in vdict['freq_cfg'][var]]))        
        return freqs
    def _get_odir(var):                                                         
        if 'odir' in vdict:                                                     
            return vdict['odir'][var]                                           
        else:                                                                   
            return var
    ############################################################DOING SOMETHING
    for var in vvv_:
        freqs = _get_freq(var)
        #freqs = ['Nov', 'Dec']
        odir_ = _od0(_get_odir(var))
        odir__ = _od1(_get_odir(var))
        os.makedirs(odir_, exist_ok=True)
        os.makedirs(odir__, exist_ok=True)
        for freq in freqs:
            t000 = l__('{} >>>>>> {}'.format(var, freq))
            a, dn = load_clmidx_(idir, var, gwls=gg, freq=freq, rn=rn,
                                 newestV=True, **lD)
            ######################################################fixing SNWmax
            if var in ['SNWmax', 'R5OScw', 'R1OScw']:
                a, dn = slct_cubeLL_dnL_(a, dn, slctStrL_, excl='KNMI')
            ######################################################fixing SNWmax
            ll_('< load', t000)
            if len(dn) == 0:
                continue
            sc, unit = sc_unit_clmidx_(a[0][0], var)
            #id__(a, dn, gwls, sc, unit, odir_, var, freq, shp, shp_)
            if opt_ == 0:
                id__(a, dn, gwls, sc, unit, odir_, var, freq, shp, shp_,
                     fig_dict=figD)
                ll_('<< id', t000)
                ts = get_ts_clmidx_(a, dn, sc, poly=sv, **tsD)
                ll_('< ts', t000)
                bp__(ts, dn, unit, gwls, odir_, var, freq, opt='02', ap=None)
                ll_('<< bp', t000)
            else:
                for i in list(rdict[opt_].keys()):
                    ts = get_ts_clmidx_(a, dn, sc, rgD=rdict[opt_][i], **tsD)
                    ll_('< ts {}'.format(i), t000)
                    bp__(ts, dn, unit, gwls, odir_, var, freq, opt='02', ap=i)
                    ll_('<< bp {}'.format(i), t000)
            am, ai, bm, bi = _q_file(odir__, a, sc, freq, gg, cref=cref)
            ll_('< clm', t000)
            #map__(am, ai, bm, bi, dn, gwls, unit, rg_dict, odir_, var, freq)
            map__(am, ai, bm, bi, dn, gwls, unit, rD_map, odir_, var, freq,
                  **mD)
            ll_('<< map', t000)


if __name__ == '__main__':
    start_time = time.time()
    main()
    logging.info(' ')
    logging.info(' {:_^42}'.format('end of program'))
    logging.info(' {:_^42}'.format('TOTAL'))
    logging.info(' ' + rTime_(time.time() - start_time))
    logging.info(strftime(" %a, %d %b %Y %H:%M:%S +0000", localtime()))
